name: tests # имя для рабочего процесса
on: push # триггер запускающий рабочий процесс, в данном случае запуск происходит при внесении изменений в репозиторий
jobs: # если необходимо запустить несколько процессов параллельно, создаётся несколько jobs
  build: # ID jobs определитель для задания, при необходимости может использоваться для создания сценариев
    name: build # имя которое будет отображаться в пользовательском интерфейсе GitHub
    runs-on: ubuntu-latest # операционная система для рабочего процесса
    steps:
    - uses: actions/checkout@v3
    - run: ls 
    
