<<<<<<< HEAD
name: function_tests 
on: push 
=======
name:function_tests 
on:push 
>>>>>>> e6b60d2 (gh actions functiontest)
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: make install
      - run: make test
